# -*- coding: utf-8 -*-
"""(0-0)Hello World

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DiVNjPWZFF1RGyKc-q0QWwyhYgtw_67l
"""

print('Hello World')